# Window Constants
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "Attacking Square"

# Rectangle properties
RECT_WIDTH = 50
RECT_HEIGHT = 50
MOVEMENT_SPEED = 5

DOOR_WIDTH = 60
DOOR_HEIGHT = 100

#Item Size
ITEM_WIDTH = 30
ITEM_HEIGHT = 15

#Weapons
Dagger = 100